version: '3.8'

services:
  mlflow:
    build:
      context: .
      dockerfile: dockerfile
    container_name: mlflow
    hostname: mlflow
    volumes:
      - ./notebooks:/app/notebooks
      - ./models:/app/models
      - ./scripts:/app/scripts
      - ./Data:/app/Data
      - ./01-intro:/app/01-intro
      - ./tracking:/app/tracking
    environment:
      - MLFLOW_ARTIFACT_ROOT=/app/tracking/mlflow_artifacts
    ports:
      - "8000:8000"
      - "5000:5000"
